- name: redis 
  hosts: redis
  become: yes
  tasks:
  - name: disabling the redis
    ansible.builtin.dnf:
      name: redis
      state: absent
  
  - name: Enabling the redis
    ansible.builtin.command: dnf module enable redis:7 -y

  - name: Installing the redis
    ansible.builtin.dnf:
      name: redis
      state: present

  - name: Allow remote connnections
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: start and enable redis
    ansible.builtin.service:
      name: redis
      state: started
      enabled: yes
      