- name: Shipping Component
  hosts: shipping 
  become: yes
  tasks:
  - name: disabling the nodejs
    ansible.builtin.dnf:
      name: maven
      state: present

  - name: creating the /app directory
    ansible.builtin.file:
      path: /app 
      state: directory

  - name: creating the non-system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: Download the Shipping zip file 
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
      dest: /tmp/shipping.zip

  - name: Extract the Shipping file
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip